[layout]
folder = "theme"
skeleton = "theme/layout.html"
output = "public"


[references]
author = "Keestra"
file = "references.bib"
[references.topics]
"Endocrinology & Early development" = "Research on human biology and development, including health, nutrition, and disease prevention. This encompasses studies on endocrine system function, particularly thyroid health and its role in early development, reproductive epidemiology, and the long-term effects of early life exposures on health outcomes. Research in this area examines how environmental factors, nutrition, and developmental processes interact to shape health trajectories from conception through childhood and into adulthood. This includes investigations into evolutionary medicine perspectives on human health, the role of hormones in development and disease, and the impact of early life conditions on later health outcomes."
"Access to Medicine & Global Health" = "Research on global health and access to health technologies, including vaccines, diagnostics, and treatments. This field addresses the critical challenges of ensuring equitable access to essential medicines and health technologies worldwide, particularly in low- and middle-income countries. Research focuses on understanding and addressing barriers to access, including intellectual property rights, pricing mechanisms, technology transfer practices, and the role of universities and public institutions in the biomedical innovation ecosystem. This includes studies on antimicrobial resistance, One Health approaches to disease prevention, and the development of sustainable solutions for global health challenges."
"Clinical Trial Transparency & Research Ethics" = "Research on clinical trial transparency and research ethics, including trial registration and reporting. This area examines the ethical and practical aspects of ensuring that clinical research is conducted transparently and that results are made publicly available in a timely manner. Research focuses on identifying gaps in trial reporting practices, evaluating the effectiveness of policies and interventions to improve transparency, and understanding the role of various stakeholders including universities, funders, and regulatory bodies in promoting research integrity. This includes studies on the impact of missing trial data on evidence-based medicine, the development of tools and frameworks for monitoring compliance, and the implementation of best practices for clinical trial transparency across different jurisdictions and institutions."


[[experience]]
title = "Research Assistant at the Department of Global Health and Development and Antimicrobial Resistance Centre"
institution = "London School of Hygiene and Tropical Medicine"
description = "Systematic review of structural interventions in WASH/biosecurity to reduce AMR burden in LMICs from a One Health perspective."
years = "2020 - 2021"
logo = "lshtm.svg"
[[experience]]
title = "Research Assistant at the School of Anthropology and Museum Ethnography"
institution = "University of Oxford"
description = "Understanding the natural variation in thyroid function using an evolutionary ecology framework and medical anthropology perspectives."
years = "2019 - 2021"
logo = "oxford.svg"
[[experience]]
title = "Research Assistant at the Bangladeshi Migrants Diet & Anthropometrics Study"
institution = "Durham University"
description = "Analysing data on different generations of Bangladeshi migrants to north London to analyse obesogenic changes in diet and lifestyle to design culturally appropriate public health interventions."
years = "2021"
logo = "durham.webp"
[[experience]]
title = "Research Assistant at the South Omo Food Security & Health Study"
institution = "Durham University"
description = "Analysing data on health and child nutritional status in a nomadic agro-pastoralist population in South-Western Ethiopia in the context of government-led sedentarisation."
years = "2020"
logo = "durham.webp"
[[experience]]
title = "Laboratory Assistant Parent-Infant Sleeping Lab"
institution = "Durham University"
description = "Volunteered on studies looking at the effect of swadling and nighttime breastfeeding on sleeping behaviours of mother's and their babies."
years = "2018 - 2019"
logo = "durham.webp"
[[experience]]
title = "Research Assistant Health and Wellbeing in Transitioning Hunter-Gatherers of the Congo Basin"
institution = "University College London"
description = "Fieldwork for two months in Congo-Brazzaville on the health and nutrition of Mbendjele hunter-gatherers."
years = "2018"
logo = "ucl.svg"
[[experience]]
title = "Research Intern Molecular And Cultural Evolution (MACE) lab"
institution = "University College London"
description = "Assisted a PhD student on her research on human genetic adaptation to dietary change, learning R studio, cleaning dietary databases."
years = "2017 - 2018"
logo = "ucl.svg"
[[experience]]
title = "Fieldwork in Burgos, Spain"
institution = "Atapuerca Foundation"
description = "Bioarcheological fieldwork at the excavation site in Western Europe with the oldest human remains near Burgos, Spain."
years = "2017"
logo = "atapuerca.svg"

[[education]]
degree = "MD/PhD in Reproductive Epidemiology and Paediatric Endocrinology"
institution = "Amsterdam UMC (AMC)"
years = "2021-2025"
description = "Alternating PhD research on the developmental plasticity of the thyroid axis with a MD in medicine. Funded by the Amsterdam UMC, Amsterdam Reproduction & Development Institute, and Stichting Steun Emma Kinderziekenhuis."
thesis = "Too much too soon, too little too late: iodine and thyroid health in the first thousand days of life and its developmental consequences"
supervisors = [
    "Prof. Tessa Roseboom (Main Promotor, Epidemiology & Data Science, AMC)",
    "Dr. Martijn Finken (Co-promotor, Paediatric endocrinology, Emma Children's Hospital)",
    "Dr. Alexandra Alvergne (Institute for Evolutionary Sciences, Montpellier University & University of Oxford)",
    "Austin Argentieri (Massachusetts General Hospital, Harvard University)",
]
logo = "amc.svg"
[[education]]
degree = "Graduate Entry Medicine"
institution = "University of Amsterdam"
years = "2020-2021"
description = "Accelerated bachelor's degree covering the first three years of medical school within 1 year."
logo = "uva.svg"
[[education]]
degree = "MSc Medical Anthropology"
distinction = "Distinction"
institution = "Durham University"
years = "2018-2019"
thesis = "The effect of early life conditions on sexual maturation - Examining the role of stress on juvenile tempo and the gene expression of Srd5a1 in GnRH-releasing neurons."
supervisors = [
    "Prof. Gillian Bentley (Anthropology, Durham)",
    "Prof. Philippa Melamed (Molecular biology, Technion, Haifa, Israel)",
]
description = "Biocultural approaches to public and global health research."
logo = "durham.webp"
[[education]]
degree = "BSc Human Sciences"
distinction = "1st Class Honours"
institution = "University College London"
years = "2015-2018"
thesis = "Out of Balance - an interdisciplinary integration of immunological and evolutionary perspectives on the role of sex hormones in the development of autoimmune disease."
supervisors = [
    "Dr. Deniz Salali (Anthropology)",
    "Dr. Victoria Male (Infection & Immunology)",
]
logo = "ucl.svg"
[[education]]
degree = "Pre-University Program: Archaeology"
institution = "Leiden University"
years = "2014"
description = "Pre-university course on archaeological sciences for high school students (1 semester)."
[[education]]
degree = "Pre-University Program: Life Science & Technology"
institution = "Leiden University"
years = "2013"
description = "Pre-university course on cell biology for high school students (1 semester)."


[[featured_media]]
name = "The Atlantic"
logo = "the-atlantic.svg"
url = "https://www.theatlantic.com/science/archive/2023/06/dolphin-calf-communication-baby-talk/674499/?utm_source=feed"
[[featured_media]]
name = "The Guardian"
logo = "the-guardian.svg"
url = "https://www.theguardian.com/world/2022/jul/22/gaga-for-goo-goo-wellington-named-the-global-capital-of-baby-talk"
[[featured_media]]
name = "STAT News"
logo = "stat-news.svg"
url = "https://www.statnews.com/pharmalot/2022/02/24/clinical-trials-transparency-uk-fda/"
[[featured_media]]
name = "The Conversation"
logo = "the-conversation.svg"
url = "https://theconversation.com/your-environment-affects-how-well-your-medications-work-identifying-exactly-how-could-make-medicine-better-246476"
[[featured_media]]
name = "TIME"
logo = "time-magazine.svg"
url = "https://time.com/7261172/genes-vs-lifestyle-longevity-study/"
[[featured_media]]
name = "Slate"
logo = "slate.svg"
url = "https://www.slate.fr/story/231275/langage-parental-universel-etude-scientique-multiculturelle"
[[featured_media]]
name = "Quartz"
logo = "quartz.svg"
url = "https://qz.com/2006390/taxpayers-are-paying-twice-or-more-for-the-covid-19-vaccine"


[nemo]
logo = "nemo.svg"
title = "NEMO Kennislink Blog"
description = "Regular blog contributions for the Dutch Children's Science Museum NEMO, as part of the KNAW Faces of Science programme. Topics include evolutionary medicine, public health, and science for children."
url = "https://www.nemokennislink.nl/facesofscience/profiel/sarai-keestra/"
[[nemo_links]]
title = "De mysterieuze Denisovamens ontrafeld"
title_en = "The mystery of the Denisovans unraveled"
year = 2025
url = "https://www.nemokennislink.nl/publicaties/het-ontrafelen-van-de-mysterieuze-denisovamens/"
[[nemo_links]]
title = "Een kansrijke start in het leven"
title_en = "A lucky start in life"
year = 2025
url = "https://www.nemokennislink.nl/publicaties/een-kansrijke-start-in-het-leven/"
[[nemo_links]]
title = "Waarom Rosalind geen Nobelprijs wint"
title_en = "Why Rosalind doesn't win a Nobel Prize"
year = 2024
url = "https://www.nemokennislink.nl/publicaties/waarom-rosalind-niet-de-nobelprijs-wint/"
[[nemo_links]]
title = "Schaamteloos menstrueren"
title_en = "Shameless menstruation"
year = 2024
url = "https://www.nemokennislink.nl/publicaties/schaamteloos-menstrueren/"
[[nemo_links]]
title = "Lang zullen zij leven"
title_en = "Long will they live"
year = 2024
url = "https://www.nemokennislink.nl/publicaties/lang-zullen-zij-leven/"
[[nemo_links]]
title = "Weg met de bikinigeneeskunde!"
title_en = "Bikini medicine is over!"
year = 2024
url = "https://www.nemokennislink.nl/publicaties/weg-met-de-bikinigeneeskunde/"
[[nemo_links]]
title = "Waarom worden mensen ziek? Een evolutionaire blik op de gezondheid"
title_en = "Why do people get sick? An evolutionary perspective on health"
year = 2023
url = "https://www.nemokennislink.nl/publicaties/waarom-worden-mensen-ziek/"
[[nemo_links]]
title = "Een gezonde toekomst begint al voor de geboorte"
title_en = "A healthy future starts before birth"
year = 2023
url = "https://www.nemokennislink.nl/publicaties/een-gezonde-toekomst-begint-al-voor-de-geboorte/"
[[nemo_links]]
title = "Opsporing verzocht: de resultaten van medisch onderzoek zijn te vaak niet transparant"
title_en = "Investigation requested: the results of medical research are often not transparent"
year = 2023
url = "https://www.nemokennislink.nl/publicaties/opsporing-verzocht-de-resultaten-van-medisch-onderzoek-zijn-te-vaak-niet-transparant/"
[[nemo_links]]
title = "150 jaar vrouwelijke artsen in Nederland: Pioniers in de wetenschap en strijders voor de rechten van de vrouw"
title_en = "150 years of female doctors in the Netherlands: Pioneers in science and fighters for the rights of women"
year = 2022
url = "https://www.nemokennislink.nl/facesofscience/blogs/150-jaar-vrouwelijke-artsen-in-nederland/"
[[nemo_links]]
title = "Is babypraat universeel?"
title_en = "Is baby talk universal?"
year = 2022
url = "https://www.nemokennislink.nl/facesofscience/blogs/is-babypraat-universeel/"
[[nemo_links]]
title = "Waarom lopen mensen op 2 benen?"
title_en = "Why do people walk on two legs?"
year = 2022
url = "https://www.nemokennislink.nl/facesofscience/blogs/waarom-lopen-mensen-op-twee-benen/"
[[nemo_links]]
title = "Op bezoek bij de Wereldgezondheidsorganisatie"
title_en = "Visiting the World Health Organization"
year = 2022
url = "https://www.nemokennislink.nl/facesofscience/blogs/op-bezoek-bij-de-wereldgezondheidsorganisatie/"
[[nemo_links]]
title = "Zeewier, Zout en Zwangere Vrouwen - Waarom er jodium in ons zout zit"
title_en = "Seaweed, salt and pregnant women - Why iodine is in our salt"
year = 2022
url = "https://www.nemokennislink.nl/facesofscience/blogs/zeewier-zout-en-zwangere-vrouwen/"


[[media]]
title = "Food for thought: The UN Decade of Action on Nutrition at the WHO"
outlet = "People's Dispatch"
year = 2023
url = "https://peoplesdispatch.org/2023/02/04/food-for-thought-the-un-decade-of-action-on-nutrition-at-the-who/"
[[media]]
title = "Private monopolies hinder progress on public health: intellectual property at the 75th World Health Assembly"
outlet = "People's Dispatch"
year = 2022
url = "https://peoplesdispatch.org/2022/06/12/private-monopolies-hinder-progress-on-public-health-intellectual-property-at-the-75th-world-health-assembly/"
[[media]]
title = "Passing exams and planning protests — the role of students in the access to medicines movement"
outlet = "Médecins Sans Frontières (MSF)"
year = 2020
url = "https://msf-access.medium.com/passing-exams-and-planning-protests-the-role-of-students-in-the-access-to-medicines-movement-ae3b8d8d5906"
[[media]]
title = "Dutch National Radio 1, Night of Science"
outlet = "NPO Radio 1"
year = 2022
url = "https://www.nporadio1.nl/uitzendingen/de-nacht-van/4e2a6acd-5aab-4378-9e0c-b77881c7a953/2022-11-24-de-nacht-van"
[[media]]
title = "Political pressure in the U.K. prompted more universities to report clinical trial results"
outlet = "STAT News"
year = 2022
url = "https://www.statnews.com/pharmalot/2022/02/24/clinical-trials-transparency-uk-fda/"
[[media]]
title = "Access to Medicines, Vaccines and the Covid-19 Pandemic"
outlet = "The Interdisciplinarian, Harvard Public Health Review"
year = 2021
url = "https://bcphr.org/weiss-goitiandia-blog-4/"
[[media]]
title = "Africa should tackle failures in technology sharing"
outlet = "University World News"
year = 2021
url = "https://www.universityworldnews.com/post.php?story=20210519190234497"
[[media]]
title = "In the push for new vaccines, taxpayers keep paying and paying"
outlet = "Quartz"
year = 2021
url = "https://qz.com/2006390/taxpayers-are-paying-twice-or-more-for-the-covid-19-vaccine/"
[[media]]
title = "More than 1,600 clinical trials run by UK universities violate reporting rules"
outlet = "Transparimed"
year = 2020
url = "https://www.transparimed.org/single-post/2019/01/24/More-than-1600-clinical-trials-run-by-UK-universities-violate-reporting-rules"
